volumes:
  osm:
  postgis:
  osm-valhalla:

networks:
  internal:
  db:
  traefik:
    name: traefik

services:

  valhalla:
    tty: true
    stdin_open: true
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
      # entrypoint: /bin/bash
    environment:
      tile_urls: "https://download.geofabrik.de/europe/romania-latest.osm.pbf"
      server_threads: 4
    networks:
      - internal
    volumes:
      - osm-valhalla:/custom_files

  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontend-secure.entrypoints=https"
      - "traefik.http.middlewares.frontend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader2.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.frontend.middlewares=frontend-https-redirect"
      - "traefik.http.routers.frontend-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontend-secure.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    tty: true
    stdin_open: true
    build:
      context: ./containers/react-frontend/
      dockerfile: Dockerfile
    environment:
      REACT_APP_MAPBOX_TOKEN: ${REACT_APP_MAPBOX_TOKEN}
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./containers/react-frontend/src:/app/src
      - /etc/localtime:/etc/localtime

  postgis:
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGIS_PASSWORD}
      - POSTGRES_USER=${POSTGIS_USER}
      - POSTGRES_DB=${POSTGIS_DB}
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $POSTGIS_DB -U $POSTGIS_USER"
        ]
      timeout: 5s
      retries: 10
    image: postgis/postgis:16-3.4-alpine
    networks:
      - db
    restart: always
    volumes:
      - postgis:/var/lib/postgresql/data

  backend:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.backend.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.backend-rewrite.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend-secure.entrypoints=https"
      - "traefik.http.middlewares.backend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader2.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.backend.middlewares=backend-rewrite,backend-https-redirect"
      - "traefik.http.routers.backend-secure.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-secure.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
    build:
      context: ./containers/backend/
      dockerfile: Dockerfile
    depends_on:
      - postgis
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      - db
      - internal
      - traefik
    restart: unless-stopped
    command: uvicorn api:app --reload --host 0.0.0.0 --port 80
    volumes:
      # Read-only volume with source code
      - ./containers/backend/src:/app/:rw
      - /etc/localtime:/etc/localtime

  traefik:
    environment:
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}
    image: traefik:v3.2
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./containers/traefik/traefik.yml:/traefik.yml:ro
      - ./containers/traefik/tls.yml:/tls.yml:ro
      - ./containers/traefik/self_signed:/self_signed:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${DOMAIN}`) && PathPrefix(`/dashboard`)"
      - "traefik.http.middlewares.traefik-rewrite.stripprefix.prefixes=/dashboard"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-rewrite"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`${DOMAIN}`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.service=api@internal"
