volumes:
  osm:
  postgis:

networks:
  db:
  external:
    driver:
      bridge

services:
  osm-setup-1:
    image: osm-setup:0.1
    build:
      context: ./containers/osm-setup/
      dockerfile: Dockerfile
    entrypoint:
      - /usr/bin/bash
      - /app/entrypoint.sh
    volumes:
      - osm:/data/osm

  osrm:
    depends_on:
      osm-setup-1:
        condition: service_completed_successfully
    entrypoint: /data/entrypoint.sh
    image: osrm/osrm-backend
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - osm:/data
      - ./containers/osrm/entrypoint.sh:/data/entrypoint.sh

  frontend:
    environment:
      - TZ=${TZ}
    image: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./containers/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./containers/frontend/html:/usr/share/nginx/html

  postgis:
    container_name: geo-db
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGIS_PASSWORD}
      - POSTGRES_USER=${POSTGIS_USER}
      - POSTGRES_DB=${POSTGIS_DB}
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $POSTGIS_DB -U $POSTGIS_USER"
        ]
      timeout: 5s
      retries: 10
    image: postgis/postgis:16-3.4-alpine
    networks:
      - db
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    volumes:
      - postgis:/var/lib/postgresql/data

  backend:
    build:
      context: ./containers/backend/
      dockerfile: Dockerfile
    depends_on:
      - postgis
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      - db
      - external
    ports:
      - 127.0.0.1:8001:80
    restart: unless-stopped
    command: uvicorn api:app --reload --host 0.0.0.0 --port 80
    volumes:
      # Read-only volume with source code
      - ./containers/backend/src:/app/:ro


