volumes:
  osm:
  postgis:
  osm-valhalla:
  traefik-certs:

networks:
  internal:
  db:
  traefik:
    enable_ipv6: true
    name: traefik

services:

  valhalla:
    tty: true
    stdin_open: true
    # Linux arm64 v3.5.1
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:3.5.1@sha256:77f4f2695b647892b493aa35af74edfba386fcf6a3cafd38b87f2f566639916c
      # entrypoint: /bin/bash
    environment:
      tile_urls: "https://download.geofabrik.de/europe/romania-latest.osm.pbf"
      server_threads: 4
    networks:
      - internal
    volumes:
      - osm-valhalla:/custom_files

  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontend-secure.entrypoints=https"
      - "traefik.http.middlewares.frontend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader2.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.frontend.middlewares=frontend-https-redirect"
      - "traefik.http.routers.frontend-secure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontend-secure.tls=true"
      - "traefik.http.routers.frontend-secure.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.frontend-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    depends_on:
      - traefik
    tty: true
    stdin_open: true
    build:
      context: ./containers/react-frontend/
      dockerfile: Dockerfile
      args:
        - REACT_APP_MAPBOX_TOKEN=${REACT_APP_MAPBOX_TOKEN}
        - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
        - REACT_APP_GOOGLE_MAPS_API_KEY=${REACT_APP_GOOGLE_MAPS_API_KEY}
    environment:
      REACT_APP_MAPBOX_TOKEN: ${REACT_APP_MAPBOX_TOKEN}
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
      REACT_APP_GOOGLE_MAPS_API_KEY: ${REACT_APP_GOOGLE_MAPS_API_KEY}
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - ./containers/react-frontend/src:/app/src
      - /etc/localtime:/etc/localtime

  postgis:
    environment:
      - POSTGRES_PASSWORD=${POSTGIS_PASSWORD}
      - POSTGRES_USER=${POSTGIS_USER}
      - POSTGRES_DB=${POSTGIS_DB}
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $POSTGIS_DB -U $POSTGIS_USER"
        ]
      timeout: 5s
      retries: 10
    image: tobi312/rpi-postgresql-postgis:16-3.4-alpine-arm64
    networks:
      - db
    restart: always
    volumes:
      - postgis:/var/lib/postgresql/data

  backend:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.backend.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.backend-rewrite.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend-secure.entrypoints=https"
      - "traefik.http.middlewares.backend-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader2.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.backend.middlewares=backend-rewrite,backend-https-redirect"
      - "traefik.http.routers.backend-secure.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend-secure.tls=true"
      - "traefik.http.routers.backend-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=80"
    build:
      context: ./containers/backend/
      dockerfile: rpi.Dockerfile
    depends_on:
      - traefik
      - valhalla
      - postgis
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "1"
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      - db
      - internal
      - traefik
    restart: unless-stopped
    command: uvicorn api:app --reload --host 0.0.0.0 --port 80
    volumes:
      # Read-only volume with source code
      - ./containers/backend/src:/app/:rw
      - /etc/localtime:/etc/localtime

  traefik:
    environment:
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}
      TZ: 'Europe/Bucharest'
    image: arm64v8/traefik:latest
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    security_opt:
      - no-new-privileges=true
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/certs
      - ./containers/traefik/traefik.yml:/traefik.yml:ro
    labels:
      - "traefik.enable=true"
