log:
  level: DEBUG

api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    transport:
      respondingTimeouts:
         readTimeout: 3600
         writeTimeout: 3600

    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    transport:
      respondingTimeouts:
         readTimeout: 3600
         writeTimeout: 3600

serversTransport:
  insecureSkipVerify: true

tcpServersTransport:
  dialTimeout: 3600s

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letencrypt:
    acme:
      email: poptrb1@gmail.com
      storage: /certs/acme.json
      # caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      httpChallenge:
        entryPoint: http
